### ISSUE TITLE
Db importing is taking so long

### ISSUE THREAD

**Issue by ajimatahari** [marcoax/maguttiCms#11]
it doesn say error or anything. but this is the 4th hours of importing the db sql

**Comment by marcoax** [comment]
Hi, it's really strange. Usually it's take about a minute in muratura località machine

**Comment by ajimatahari** [comment]
been trying 6 times... with desktop client and phpMyAdmin and different mysql-Server... i don't know why... but it's doesn't show any error...  still hours for importing

**Comment by ajimatahari** [comment]
i give up trying... why there's no database seeder on this project.. i hope you built it... :)
