### ISSUE TITLE
Image source not readable

### ISSUE THREAD

**Issue by r-chrzan** [marcoax/maguttiCms#16]
Hi!
I get an error: Intervention \ Image \ Exception \ NotReadableException Image source not readable, after following the instructions. Can the fault lie on the server configuration side?

**Comment by marcoax** [comment]
Hi,
Where do you see the problem?

Il giorno mar 12 feb 2019, 22:20 r-chrzan <notifications@github.com> ha
scritto:

**Comment by r-chrzan** [comment]
I try to open http://my-site/en

**Comment by marcoax** [comment]
Hi
I'tried locally on my Mac and seems to work

Il giorno mer 13 feb 2019, 08:21 r-chrzan <notifications@github.com> ha
scritto:

**Comment by marcoax** [comment]
Hi
Are you using Valet?

Il giorno mer 13 feb 2019, 10:01 Marco Asperti <marcoasperti@gmail.com> ha
scritto:

**Comment by r-chrzan** [comment]
No, i'm using Apache / 2.4.29 on Ubuntu and php version 7.2.15

**Comment by r-chrzan** [comment]
ok, i did it. I just added a vitrual host and it works.

**Comment by marcoax** [comment]
Hi
OK good

Il giorno mer 13 feb 2019, 13:28 r-chrzan <notifications@github.com> ha
scritto:
