### ISSUE TITLE
php artisan

### ISSUE THREAD

**Issue by markib** [marcoax/maguttiCms#3]
if we run from cmd prompt.i get this

[Window Title]
CLI

[Main Instruction]
CLI has stopped working

[Content]
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

[Close program]

**Comment by marcoax** [comment]
Hi
Try ti install a fresh copy of laravel
And check in you have the same issue


Il 17 feb 2017 12:19 PM, "Bikram Maharjan" <notifications@github.com> ha
scritto:
