### ISSUE TITLE
REDIS_PREFIX error

### ISSUE THREAD

**Issue by smartnathan** [marcoax/maguttiCms#42]
I am having this error `REDIS_PREFIX not specified. App killed`

**Comment by marcoax** [comment]
Hi,

I've  fixed  the issue  in the last release 
ADD CACHE_PRIFIX in your   .env  file

In alternative you can fix  it adding REDIS_PREFIX in your  .env  file

**Comment by marcoax** [comment]
Hi
Fixed
Please download the latest version


Il gio 24 set 2020, 08:55 Nathaniel David <notifications@github.com> ha
scritto:

**Comment by smartnathan** [comment]
Thank you, I do appreciate it. That solved it.

**Comment by marcoax** [comment]
Hi thanks
Have a nice day
Marco

Il gio 24 set 2020, 10:00 Nathaniel David <notifications@github.com> ha
scritto:
