### ISSUE TITLE
Invalid request (Unsupported SSL request)

### ISSUE THREAD

**Issue by ayoubkhan558** [marcoax/maguttiCms#44]
[Tue Nov 17 19:30:00 2020] 127.0.0.1:63967 Invalid request (Unsupported SSL request)

![image](https://user-images.githubusercontent.com/20210961/99402709-7ce10e80-289e-11eb-8b45-a271cf9e8a5e.png)

How to solve this issue?

**Comment by marcoax** [comment]
Hi
 in you .env
 set
APP_HTTPS=false

Il giorno mar 17 nov 2020 alle ore 15:31 Muhammad Ayoub Khan <
notifications@github.com> ha scritto:
