### ISSUE TITLE
Sql script framework_base.sql don't work with PostgreSQL

### ISSUE THREAD

**Issue by ijurisic** [marcoax/maguttiCms#45]
When try import framework_base.sql I have lot errors on my PostgreSQL 11 database. I think that script is for MySQL?

Any chance to create script for PostgreSQL?

**Comment by marcoax** [comment]
Hi,
At the moment the only db supported is mysql

Il gio 10 dic 2020, 13:29 ijurisic <notifications@github.com> ha scritto:
