### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by tonybyng** [marcoax/maguttiCms#47]
Hi.

I 've just installed by git cloning, composer install, updating .env with database details and importing the db sql file as requested. The first issue I get is that it complains that I havent got redis available, so I set up redis and get in.  I then go to add a new test page to see how it works and I get a database error saying 

Column not found: 1054 Unknown column 'footer_menu' in 'field list' (SQL: update `articles` set `footer_menu` = 0, `articles`.`updated_at` = 2020-12-24 10:30:56 where `id` = 1)

I check the migrations and see it there and so I manually add it to the articles table as a boolean and I get to save the page.  I then try to add a news item and I get

Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' (SQL: insert into `news_translations` (`locale`, `title`, `subtitle`, `slug`, `description`, `seo_title`, `seo_description`, `news_id`, `updated_at`, `created_at`) values (it, ?, ?, , ?, ?, ?, 0, 2020-12-24 10:34:27, 2020-12-24 10:34:27))

I look and I see news_translations isnt in the migrations so I check the structure and see that the id is not an auto increment.  Usually if the id is set as the primary key its usually an auto increment, I set it an auto increment and tried again

I then got

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' (SQL: insert into `news` (`date`, `date_start`, `sort`, `pub`, `image`, `doc`, `updated_at`, `created_at`) values (2020-12-24 00:00:00, 2020-12-24 00:00:00, ?, 1, ?, ?, 2020-12-24 10:42:02, 2020-12-24 10:42:02))

and so saw the same problem with the news table so set that as an auto increment on the id as well and got to save the news item

Ive taken a look at the framework_base.sql and these ids are not set to be auto increment so its not like it had issues when it pulled in the sql file.

I don't know if I will hit any other problems but I thought I'd highlight these for you.

Hope that helps

**Comment by marcoax** [comment]
Hi thank,
I fix it as soon as possible


Il gio 24 dic 2020, 10:50 Tony Byng <notifications@github.com> ha scritto:

**Comment by tonybyng** [comment]
Hi

Thanks for the quick response!. Ive taken a quick look at the sql file and I can see carts doesnt have an auto inc (or a primary key), and newsletters is missing the auto inc (but does have a primary key) so Im going to assume those are the same as above and set them up with a primary key and auto inc in the hope that fixes any other issues I might see.

**Comment by marcoax** [comment]
Hi
Did install the master version?

Il gio 24 dic 2020, 11:00 Tony Byng <notifications@github.com> ha scritto:

**Comment by tonybyng** [comment]
Hi
Yes I can only see a master branch anyway and I didnt select any previous tags. I actually forked the repo and then did a git clone of my repo in case I did any changes that might be worth a PR, but Ive just taken a look at https://github.com/marcoax/maguttiCms/blob/master/db/framework_base.sql and I can see the news table has not got the auto inc on the id for example.

**Comment by marcoax** [comment]
Hi
I've fixed all the auto inc missing keys
If you want to test upload the new https://github.com/marcoax/maguttiCms/blob/master/db/framework_base.sql  file

**Comment by marcoax** [comment]
Hi,
 seems. I've fixed all the installation issues
