### ISSUE TITLE
REDIS_PREFIX not specified. App kille

### ISSUE THREAD

**Issue by asimshazad** [marcoax/maguttiCms#5]
After installing,i am getting this error,when i try to access it.

**Comment by marcoax** [comment]
Hi try ti remove resistenza from the .env file

**Comment by asimshazad** [comment]
Can you please elaborate what is "resistenza",there is no entry with such name in .env

**Comment by asimshazad** [comment]
By removing Redis entries in .env,i can access now,but still there is errors in carousel.blade.php

**Comment by marcoax** [comment]
Hi, I've  fix the carousel.blade.php bugs
Pleas update your version

**Comment by asimshazad** [comment]
Thank you for the quick reply and fix.
I have downloaded the fresh copy,now i am facing the following errors.

1) After login i am getting "TokenMismatchException" error.
2) Image source not readable on frontpage.
3) Sql syntex error,while importing sql.
#1452 - Cannot add or update a child row: a foreign key constraint fails (`quizz`.`#sql-27a_701`, CONSTRAINT `role_user_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)

Can you please have a look into these issues as well ?
Thank you

**Comment by marcoax** [comment]
Hi
1) After login i am getting "TokenMismatchException" error ?
are you try to login to admin or front-end
2) Image source not readable on frontpage
please  check if placeholder.png is present in this  folder /public/image/media/
3)Sql syntax error,while importing sql.
I'll try to fix  this

**Comment by asimshazad** [comment]
1) I am tring to login through admin

But i can access the url when run the command "php artisan serve",it seems you have used "symlink"?

**Comment by marcoax** [comment]
Hi 
3)Sql syntax error,while importing sql.
fixed

**Comment by marcoax** [comment]
Hi, 
I'm using  Valet on Mac, anyway  I've  tried on windows too without any problem

**Comment by asimshazad** [comment]
I am using Mac as well.
Thank you,its working fine now

**Comment by marcoax** [comment]
Ok finr
