### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by ahangarha** [marcoax/maguttiCms#58]
Please consider adding license to the project otherwise it is proprietary software not a Free/Libre and Open Source software.

**Comment by emaalouf** [comment]
The code is covered under MIT License, written in the bottom of the page! Please Check!
Elias

**Comment by ahangarha** [comment]
The established convention is to have LICENSE or COPYING file in the root of the repo and keep licenses text in them. It is the norm to keep a copy of license in the project. It can be added with few clicked on Github.

**Comment by emaalouf** [comment]
I agree, let's tag the author to do so @marcoax

**Comment by marcoax** [comment]
Added MIT LICENSE
