### ISSUE TITLE
Adding roles causes this error.

### ISSUE THREAD

**Issue by emaalouf** [marcoax/maguttiCms#59]
Hi, I just found this CMS and it is a life saving amazing CMS. I would like to be able to add roles but I am having this error, I am trying to debug it and submit where the error is:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'level' in 'field list' (SQL: insert into `roles` (`name`, `display_name`, `description`, `level`, `updated_at`, `created_at`) values (Vendor, Vendor, Vendor, 5, 2021-05-24 14:04:38, 2021-05-24 14:04:38))

If anyone else finds it first, please report it so we can fix this the soonest.
Elias

**Comment by marcoax** [comment]
Hi,
Pleasse Add the level filed ti the roles table
I'll fix It in the next release


Il lun 24 mag 2021, 14:06 Elias Maalouf ***@***.***> ha
scritto:

**Comment by marcoax** [comment]
Hi 
 I've added the level filed to db/framework_base.sql file.
