### ISSUE TITLE
problem while composer install.

### ISSUE THREAD

**Issue by gwachhamit** [marcoax/maguttiCms#63]
I am using php 8.0.6.
While running `composer install` command, it shows following errors.
`Problem 1
    - Root composer.json requires php ^7.4 but your php version (8.0.6) does not satisfy that requirement.
  Problem 2
    - lcobucci/jwt is locked to version 3.3.3 and an update of this package was not requested.
    - lcobucci/jwt 3.3.3 requires php ^5.6 || ^7.0 -> your php version (8.0.6) does not satisfy that requirement.
  Problem 3
    - magutti/magutti-builders is locked to version dev-master and an update of this package was not requested.
    - magutti/magutti-builders dev-master requires php ^7.1 -> your php version (8.0.6) does not satisfy that requirement.
  Problem 4
    - phpoffice/phpspreadsheet is locked to version 1.18.0 and an update of this package was not requested.
    - phpoffice/phpspreadsheet 1.18.0 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
  Problem 5
    - tymon/jwt-auth is locked to version 1.0.2 and an update of this package was not requested.
    - tymon/jwt-auth 1.0.2 requires php ^5.5.9|^7.0 -> your php version (8.0.6) does not satisfy that requirement.
  Problem 6
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.6) does not satisfy that requirement.
  Problem 7
    - phpoffice/phpspreadsheet 1.18.0 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - maatwebsite/excel 3.1.31 requires phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0].
    - maatwebsite/excel is locked to version 3.1.31 and an update of this package was not requested.`
    
[Error Picture](http://i.prntscr.com/VhfCltY8RcqcipuivEce4w.png)

**Comment by marcoax** [comment]
Hi
Seems some package used in Magutti not support PHP 8
Try to use PHP 7.4
In addition seems you don't have
Installed the gd library on your machine


Il ven 30 lug 2021, 04:51 amit gwachha ***@***.***> ha
scritto:
