### ISSUE TITLE
Problem with CSRF

### ISSUE THREAD

**Issue by Melki-Sap** [marcoax/maguttiCms#64]
Hai, i install using git clone dan composer install.

But when i try to open to login in the admin panel (http://yourpath/admin), it got error CSRF token mismatch.

Hope you can help me. Thank you.

**Comment by marcoax** [comment]
Hi
Try to run from the console php artisan key:generate

Il sab 31 lug 2021, 19:28 Melki Saputro ***@***.***> ha
scritto:

**Comment by Melki-Sap** [comment]
Hai Marcoax,

Thank you for your respond, anyway the problem i have found it but i can not fix it. So now i trying to set it into Redis not files.

Hope this help anyone that have the same problem like me.
