### ISSUE TITLE
Error publish news

### ISSUE THREAD

**Issue by yuri25** [marcoax/maguttiCms#7]
Illuminate \ Database \ QueryException (23000)
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'doc' cannot be null (SQL: insert into `news` (`date`, `sort`, `pub`, `image`, `doc`, `updated_at`, `created_at`) values (2017-10-21 02:50:24, 3, 1, 13850371370-cr-1920x1200.jpg, , 2017-10-21 02:51:13, 2017-10-21 02:51:13))

**Comment by marcoax** [comment]
Hi,
 fix  the  issue  runnig
 ALTER TABLE `news` CHANGE `doc` `doc` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL;

 this set as nullable the doc  field

 by the  way i've just commit a  fix in the  repo
