### ISSUE TITLE
getting  TypeError issue

### ISSUE THREAD

**Issue by mangal1018** [marcoax/maguttiCms#70]
when I use composer install command then it tell update composer so I update composer.
then it through error (see attached screenshot )
![typeError](https://user-images.githubusercontent.com/47784230/143883687-aa914ae8-ba04-4bcb-9ac3-58178eb990f1.png)

**Comment by marcoax** [comment]
Hi
Add the app_name in your .env file

Il lun 29 nov 2021, 15:17 Mangal ***@***.***> ha scritto:

**Comment by marcoax** [comment]
Hi,
which is you php version?  8 or 7.4 ?

**Comment by marcoax** [comment]
Hi ,
if you are  on PHP 7.4  replace
private mixed $app_name;
to 
private string $app_name;
in app\Console\Commands\InstallMaguttiDb

**Comment by mangal1018** [comment]
Hi There
I extremely very happy to using your platform.
you solved my problem very fast response I got.
Thank you very much

**Comment by marcoax** [comment]
:))
