### ISSUE TITLE
Error occur during users deletions

### ISSUE THREAD

**Issue by vanji-code** [marcoax/maguttiCms#72]
**What version of this package are you using?**
maguttiCms 8.73.1 - 8.0.6
**What operating system, Node.js, and npm version?**
Windows 10, node - v17.1.0, npm - 8.1.4
**What happened?**
I have tried "Add" Users and Admins Option. But I am Unable to delete the User ID that was created. the error says

"TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given"

.. \app\maguttiCms\Permission\GFEntrustUserTrait.php:69

  static::deleting(function($user) {

            **if (!method_exists(Config::get('auth.model'), 'bootSoftDeletes'))** {

                $user->roles()->sync([]);

            }

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by marcoax** [comment]
Fix - see
https://github.com/marcoax/maguttiCms/commit/3d5382a2c8a77a4c81d901db45a8ad29108dbfde
