### ISSUE TITLE
error occurs during product "add"

### ISSUE THREAD

**Issue by vanji-code** [marcoax/maguttiCms#73]
**What version of this package are you using?**
maguttiCms 8.73.1 - 8.0.6
**What operating system, Node.js, and npm version?**
Windows 10, node - v17.1.0, npm - 8.1.4
**What happened?**
I have tried "Add" Option in Products. But I am Unable to add the Products. it shows error

"ErrorException
Attempt to read property "slug:en" on null (View: C:\xampp\htdocs\roto\resources\views\admin\common\side_bar_action.blade.php)

C:\xampp\htdocs\roto\app\maguttiCms\SeoTools\SeoPermalinkResolver.php:16

 **$trans_url = str_replace('{category}', $this->category->{'slug:'.$locale}, $trans_url);**

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by marcoax** [comment]
Hi
Fixe see https://github.com/marcoax/maguttiCms/commit/f9492f36f7687b9166fc281d51ad1d2b1b9a55e8

**Comment by vanji-code** [comment]
Thank you now its working.

**Comment by marcoax** [comment]
Top

Il dom 5 dic 2021, 17:48 vanji-code ***@***.***> ha scritto:
