### ISSUE TITLE
.env APP_HTTPS=true but still not loading https

### ISSUE THREAD

**Issue by how1e** [marcoax/maguttiCms#75]
**What version of this package are you using?**
v9.0.5

**What operating system, and npm version?**
- AWS AMI2
- npm v8.0.0

**What happened?**
Set APP_HTTPS in .env file to true but when loading the pages, images,stylesheets,fonts are loaded over http which are blocked by browser.

**What did you expect to happen?**
The images,stylesheets,fonts etc should be loaded over https instead.

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by marcoax** [comment]
Your web server it's configured for https?
You are on local  machine ?
