### ISSUE TITLE
autoload

### ISSUE THREAD

**Issue by endarphysics** [marcoax/maguttiCms#76]
I get an error when installing Magutti
Warning: require(C:\xampp\htdocs\magutti/vendor/autoload.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\magutti\index.php on line 23

Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs\magutti/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\magutti\index.php:23 Stack trace: #0 {main} thrown in C:\xampp\htdocs\magutti\index.php on line 23

**Comment by marcoax** [comment]
Hi
please check if you have C:\xampp\htdocs\magutti/vendor/autoload.php this  in vendor folder

did you run composer dumpautoload?
