### ISSUE TITLE
hpslider link not working

### ISSUE THREAD

**Issue by vanji-code** [marcoax/maguttiCms#77]
**What version of this package are you using?**
maguttiCms 8.73.1 - 8.0.6
**What operating system, Node.js, and npm version?**
Windows 10, node - v17.1.0, npm - 8.1.4
**What happened?**
I have tried to add slider link in "slides" section everything saved sucessfully. but link is not applied.

              <div class="swiper-slide">
                    <img src="{{ ImgHelper::get_cached($slide->image, ['w' => 1920, 'h' => 600, 'c' => 'cover', 'q' => 70]) }}"
                         alt="" class="img-fluid">
                    <div class="swiper-slide-text">
                        <div class="container">
                            <h2 class="text-primary">{{ $slide->title }}</h2>
                            <div class="lead">{{ $slide->description }}</div>
                        </div>
                    </div>
                </div>

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by marcoax** [comment]
Added support to button in Hpslider model
https://github.com/marcoax/maguttiCms/commit/3b2e9dc810b7a460e50218085c86b79b1750c8b3
