### ISSUE TITLE
issue at live hosting, is there any update required for live hosting?

### ISSUE THREAD

**Issue by vanji-code** [marcoax/maguttiCms#78]
**What version of this package are you using?**

**What operating system, Node.js, and npm version?**

**What happened?**
it show 
favicon with "500 internal server error"

"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@demo.cms.com to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log."

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by marcoax** [comment]
Hi,
Error is quote generic
Did you configured the .env file?


Il lun 20 dic 2021, 07:11 vanji-code ***@***.***> ha scritto:

**Comment by vanji-code** [comment]
Yes, I did, like

.env file
======

APP_NAME=democms
APP_ENV=local
APP_KEY=base64:+VTfPXpCs4IPm8dSmqiqj3h1jQa1oXRJuV2iLkpAYsw=
APP_DEBUG=true
APP_URL=http://democms.com/

LOG_CHANNEL=daily
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=democms
DB_USERNAME=democms
DB_PASSWORD=**********

BROADCAST_DRIVER=log
CACHE_DRIVER=array
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

#MEMCACHED_HOST=127.0.0.1

#With Redis
#REDIS_HOST=127.0.0.1
#REDIS_PASSWORD=null
#REDIS_PORT=6379
#REDIS_CLIENT=predis

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

#MAGUTTI CMS  CONFIG
APP_HTTPS=false #set to true to force HTTPS
ASSET_PUBLIC_PATH=  #if you are on shared hosting typlically public/

ERRORS_DB=false
ERRORS_MAIL=false

PAYPAL_MODE=sandbox
PAYPAL_SANDBOX_API_USERNAME=
PAYPAL_SANDBOX_API_PASSWORD=
PAYPAL_SANDBOX_API_SECRET=

PAYPAL_LIVE_API_USERNAME=
PAYPAL_LIVE_API_PASSWORD=
PAYPAL_LIVE_API_SECRET=

APP_EDITOR =phpstorm


FACEBOOK_CLIENT_ID=XXXXXXX
FACEBOOK_CLIENT_SECRET=XXXXXXX
FACEBOOK_CALLBACK_URL=https://magutticms.test/social_auth/facebook/callback

GOOGLE_CLIENT_ID=XXXXXXX
GOOGLE_CLIENT_SECRET=XXXXXXX
GOOGLE_CALLBACK_URL=http://127.0.0.1:8000/social_auth/google/callback

.htaccess
======
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ public/$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ public/index.php [L]
    
     # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

</IfModule>
<FilesMatch "^\.env">
    Order allow,deny
    Deny from all
</FilesMatch>

# php -- BEGIN cPanel-generated handler, do not edit
# Set the “ea-php80” package as the default “PHP” programming language.
<IfModule mime_module>
  AddHandler application/x-httpd-ea-php80 .php .php8 .phtml
</IfModule>
# php -- END cPanel-generated handler, do not edit

index.php
======
<?php
/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels great to relax.
|
*/

require __DIR__.'/vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);

**Comment by marcoax** [comment]
Did you install the vendor?

Il lun 20 dic 2021, 09:47 vanji-code ***@***.***> ha scritto:

**Comment by vanji-code** [comment]
Yes,
 I move whole my local project to "public_html" folder and import database and configure .env, htaccess, index.php

hi,
 pls let me how to deploy this cms to live server?
 detail about - server configuration, .htaccess, index.php, .env

**Comment by marcoax** [comment]
Hi
You are on a shared hosting?

Il lun 20 dic 2021, 17:09 vanji-code ***@***.***> ha scritto:

**Comment by vanji-code** [comment]
No,

**Comment by vanji-code** [comment]
issue solved assign the
"public_path in .env"

**Comment by marcoax** [comment]
Ok good

Il mar 21 dic 2021, 06:05 vanji-code ***@***.***> ha scritto:
