### ISSUE TITLE
icon images not showed run in "http://localhost/maguttiCms/public/en" instead of "http://127.0.0.1:8000"

### ISSUE THREAD

**Issue by vanji-code** [marcoax/maguttiCms#79]
**What version of this package are you using?**
maguttiCms 8.73.1 - 8.0.6
**What operating system, Node.js, and npm version?**
Windows 10, node - v17.1.0, npm - 8.1.4
**What happened?**
I have try to run as "http://localhost/maguttiCms/public/" icon images are looking as "square boxes" all others are fine.

if I tried "http://127.0.0.1:8000" working fine.

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by marcoax** [comment]
Hi,
Try to check It all the css and font resource are loaded


Il mar 21 dic 2021, 06:33 vanji-code ***@***.***> ha scritto:

**Comment by vanji-code** [comment]
I am using,
node version: v17.2.0
npm version: 8.1.4

At the time of "npm install" i got the error,

cmd: npm install

"npm ERR! code 1
npm ERR! path C:\xampp\htdocs\maguttiCms\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js"

cmd: npm run production

> production
> mix --production

'mix' is not recognized as an internal or external command,
operable program or batch file.

**Comment by marcoax** [comment]
Hi
Node and npm are installed on your machine?

Il mar 21 dic 2021, 08:15 vanji-code ***@***.***> ha scritto:

**Comment by vanji-code** [comment]
Yes installed
I am using,
node version: v17.2.0
npm version: 8.1.4

**Comment by vanji-code** [comment]
i try the command "npm install"

npm ERR! code 1
npm ERR! path C:\xampp\htdocs\bhmcorp\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files (x86)\nodejs\node.exe C:\xampp\htdocs\bhmcorp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\xampp\\htdocs\\bhmcorp\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | win32 | ia32
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\bhmcorp\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\xampp\htdocs\bhmcorp\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\xampp\htdocs\bhmcorp\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bhmcorp\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bhmcorp\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bhmcorp\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\bhmcorp\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\xampp\htdocs\bhmcorp\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\xampp\htdocs\bhmcorp\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bhmcorp\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bhmcorp\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\xampp\htdocs\bhmcorp\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\xampp\\htdocs\\bhmcorp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\xampp\htdocs\bhmcorp\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\work\AppData\Local\npm-cache\_logs\2021-12-22T15_58_44_630Z-debug.log

**Comment by marcoax** [comment]
Hi
Try to use a differenti versioni of node
16.xx or 15.xxx

Il mer 22 dic 2021, 17:11 vanji-code ***@***.***> ha scritto:

**Comment by vanji-code** [comment]
Hi, i used 
Node - v16.13.1
npm - 8.1.2

then i installed "node_modules" successfully! but "font Awesome" icons not showed,

if i run via "php artisan serve",  "font Awesome" icons showed.

**Comment by marcoax** [comment]
Hi,
I think it's a problem
Try to copy the font folder under the site root

Il gio 23 dic 2021, 07:43 vanji-code ***@***.***> ha scritto:

**Comment by vanji-code** [comment]
Yeah! now it's working fine. thank you!
